@echo off
color 4
echo Please wait for requirements.txt to respond, Do not exit out or press ctrl + C unless you want this to fail!...
TIMEOUT /T 3 /NOBREAK
echo installing...(this may take a while)
TIMEOUT /T 2 /NOBREAK
echo installing directories...
TIMEOUT /T 2 /NOBREAK
echo installing updates...
TIMEOUT /T 2 /NOBREAK
echo installing git...
TIMEOUT /T 2 /NOBREAK
echo installing patch...
TIMEOUT /T 2 /NOBREAK
echo installing httpx...
TIMEOUT /T 2/NOBREAK
echo installing patch updates...
TIMEOUT /T 2/NOBREAK
echo istalling bx3 v2...
TIMEOUT /T 2/NOBREAK
echo Failed, updated version already installed....
TIMEOUT /T 2/NOBREAK
echo Installed Successfully!
pause